[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Critical for client-side routing and authentication redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200