/**
 * Dummy data for NCAA tournament teams
 */
const dummyTeams =  [
  // Midwest Region
  {
    team: 'Houston',
    seed: 1,
    region: 'Midwest',
    record: '30-4',
    conference: 'Big 12',
  },
  {
    team: 'Tennessee',
    seed: 2,
    region: 'Midwest',
    record: '27-7',
    conference: 'SEC',
  },
  {
    team: 'Kentucky',
    seed: 3,
    region: 'Midwest',
    record: '22-11',
    conference: 'SEC',
  },
  {
    team: 'Purdue',
    seed: 4,
    region: 'Midwest',
    record: '22-11',
    conference: 'Big Ten',
  },
  {
    team: 'Clemson',
    seed: 5,
    region: 'Midwest',
    record: '27-6',
    conference: 'ACC',
  },
  {
    team: 'Illinois',
    seed: 6,
    region: 'Midwest',
    record: '21-12',
    conference: 'Big Ten',
  },
  {
    team: 'UCLA',
    seed: 7,
    region: 'Midwest',
    record: '28-5',
    conference: 'Pac-12',
  },
  {
    team: 'Gonzaga',
    seed: 8,
    region: 'Midwest',
    record: '25-8',
    conference: 'AE',
  },
  {
    team: 'Georgia',
    seed: 9,
    region: 'Midwest',
    record: '20-12',
    conference: 'SEC',
  },
  {
    team: 'Utah St',
    seed: 10,
    region: 'Midwest',
    record: '26-7',
    conference: 'MWC',
  },
  {
    team: 'Texas/Xavier',
    seed: 11,
    region: 'Midwest',
    record: '20-12',
    conference: 'Big 12',
  },
  {
    team: 'McNeese',
    seed: 12,
    region: 'Midwest',
    record: '27-6',
    conference: 'Southland',
  },
  {
    team: 'High Point',
    seed: 13,
    region: 'Midwest',
    record: '29-5',
    conference: 'Big South',
  },
  {
    team: 'Troy',
    seed: 14,
    region: 'Midwest',
    record: '23.10',
    conference: 'Sun Belt',
  },
  {
    team: 'Wofford',
    seed: 15,
    region: 'Midwest',
    record: '19-15',
    conference: 'Southern',
  },
  {
    team: 'SIU',
    seed: 16,
    region: 'Midwest',
    record: '22-11',
    conference: 'OH Valley',
  },

  // East Region
  {
    team: 'Duke',
    seed: 1,
    region: 'East',
    record: '31-3',
    conference: 'ACC',
  },
  {
    team: 'Alabama',
    seed: 2,
    region: 'East',
    record: '25-8',
    conference: 'SEC',
  },
  {
    team: 'Wisconsin',
    seed: 3,
    region: 'East',
    record: '26-9',
    conference: 'Big Ten',
  },
  {
    team: 'Arizona',
    seed: 4,
    region: 'East',
    record: '22-12',
    conference: 'Big 12',
  },
  {
    team: 'Oregon',
    seed: 5,
    region: 'East',
    record: '24-9',
    conference: 'Big Ten',
  },
  {
    team: 'BYU',
    seed: 6,
    region: 'East',
    record: '24-9',
    conference: 'Big 12',
  },
  {
    team: "St Mary's",
    seed: 7,
    region: 'East',
    record: '28-5',
    conference: 'WCC',
  },
  {
    team: 'Miss St',
    seed: 8,
    region: 'East',
    record: '21-12',
    conference: 'SEC',
  },
  {
    team: 'Baylor',
    seed: 9,
    region: 'East',
    record: '19-14',
    conference: 'Big-12',
  },
  {
    team: 'Vandy',
    seed: 10,
    region: 'East',
    record: '20-12',
    conference: 'SEC',
  },
  {
    team: 'VCU',
    seed: 11,
    region: 'East',
    record: '28-6',
    conference: 'A10',
  },
  {
    team: 'Liberty',
    seed: 12,
    region: 'East',
    record: '29-6',
    conference: 'USA',
  },
  {
    team: 'Akron',
    seed: 13,
    region: 'East',
    record: '28-6',
    conference: 'MAC',
  },
  {
    team: 'Montana',
    seed: 14,
    region: 'East',
    record: '25-9',
    conference: 'Big Sky',
  },
  {
    team: 'Robby Mo',
    seed: 15,
    region: 'East',
    record: '26-8',
    conference: 'NEC',
  },
  {
    team: 'American/M St. Mary',
    seed: 16,
    region: 'East',
    record: '24-6',
    conference: 'MEAC',
  },

  // West Region
  {
    team: 'Florida',
    seed: 1,
    region: 'West',
    record: '30-4',
    conference: 'SEC',
  },
  {
    team: 'St John',
    seed: 2,
    region: 'West',
    record: '30-4',
    conference: 'Big East',
  },
  {
    team: 'Texas Tech',
    seed: 3,
    region: 'West',
    record: '25-8',
    conference: 'Big 12',
  },
  {
    team: 'Maryland',
    seed: 4,
    region: 'West',
    record: '25-8',
    conference: 'Big Ten',
  },
  {
    team: 'Memphis',
    seed: 5,
    region: 'West',
    record: '29-5',
    conference: 'AAC',
  },
  {
    team: 'Missouri',
    seed: 6,
    region: 'West',
    record: '22-11',
    conference: 'SEC',
  },
  {
    team: 'Kansas',
    seed: 7,
    region: 'West',
    record: '21-12',
    conference: 'Big 12',
  },
  {
    team: 'UConn',
    seed: 8,
    region: 'West',
    record: '23-10',
    conference: 'Big East',
  },
  {
    team: 'Oklahoma',
    seed: 9,
    region: 'West',
    record: '20-13',
    conference: 'SEC',
  },
  {
    team: 'Arkansas',
    seed: 10,
    region: 'West',
    record: '20-13',
    conference: 'SEC',
  },
  {
    team: 'Drake',
    seed: 11,
    region: 'West',
    record: '30-3',
    conference: 'MVC',
  },
  {
    team: 'Colorado St',
    seed: 12,
    region: 'West',
    record: '25-9',
    conference: 'PAC 12',
  },
  {
    team: 'Grand Canyon',
    seed: 13,
    region: 'West',
    record: '26-7',
    conference: 'WAC',
  },
  {
    team: 'UNC Wilmington',
    seed: 14,
    region: 'West',
    record: '27-7',
    conference: 'CAAC',
  },
  {
    team: 'Omaha',
    seed: 15,
    region: 'West',
    record: '22-12',
    conference: 'SLC',
  },
  {
    team: 'Norfolk St',
    seed: 16,
    region: 'West',
    record: '24-10',
    conference: 'MAC',
  },

  // South Region
  {
    team: 'Auburn',
    seed: 1,
    region: 'South',
    record: '28-5',
    conference: 'SEC',
  },
  {
    team: 'Michigan State',
    seed: 2,
    region: 'South',
    record: '27-6',
    conference: 'Big Ten',
  },
  {
    team: 'Iowa St.',
    seed: 3,
    region: 'South',
    record: '24-9',
    conference: 'Big 12',
  },
  {
    team: 'Texas A&M',
    seed: 4,
    region: 'South',
    record: '22-10',
    conference: 'SEC',
  },
  {
    team: 'Michigan',
    seed: 5,
    region: 'South',
    record: '29-9',
    conference: 'Big 10',
  },
  {
    team: 'Ole Miss',
    seed: 6,
    region: 'South',
    record: '22-11',
    conference: 'SEC',
  },
  {
    team: 'Marquette',
    seed: 7,
    region: 'South',
    record: '23-10',
    conference: 'Big East',
  },
  {
    team: 'Louisville',
    seed: 8,
    region: 'South',
    record: '27-7',
    conference: 'ACC',
  },
  {
    team: 'Creighton',
    seed: 9,
    region: 'South',
    record: '24-10',
    conference: 'Big East',
  },
  {
    team: 'New Mexico',
    seed: 10,
    region: 'South',
    record: '26-7',
    conference: 'Mt West',
  },
  {
    team: 'UNC',
    seed: 11,
    region: 'South',
    record: '22-13',
    conference: 'ACC',
  },
  {
    team: 'UC San Diego',
    seed: 12,
    region: 'South',
    record: '30-4',
    conference: 'Big West',
  },
  {
    team: 'Yale',
    seed: 13,
    region: 'South',
    record: '22-7',
    conference: 'Ivy',
  },
  {
    team: 'Lipscomb',
    seed: 14,
    region: 'South',
    record: '25-9',
    conference: 'ASUN',
  },
  {
    team: 'Bryant',
    seed: 15,
    region: 'South',
    record: '23-11',
    conference: 'American East',
  },
  {
    team: 'Alabama St',
    seed: 16,
    region: 'South',
    record: '19-15',
    conference: 'SAC',
  },
];

export default dummyTeams;